name = "Port Hugo"
license = "MIT"
licenselink = "https://github.com/tylersayshi/port-hugo/blob/master/LICENSE"
description = "Web Developer Portfolio"
homepage = "https://github.com/tylersayshi/port-hugo"
tags = ['personal', 'simple', 'bootstrap', 'font-awesome', 'portfolio']
features = ['bootstrap', 'responsive']
min_version = "0.60.0"
demosite = "https://compassionate-kepler-de5af1.netlify.app/"

[author]
name = "tylersayshi"
homepage = "https://puginarug.com/"
